name: Docker image CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up DockerBuildX
        uses: docker/setup-buildx-action@v3
      - name: Log in to Container registry
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
             ghcr.io/${{ github.repository_owner }}/getting-started:latest
             ghcr.io/${{ github.repository_owner }}/getting-started:${{ github.sha }}
